// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD18406_NET104.Models;

#nullable disable

namespace SD18406_NET104.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    partial class CategoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD18406_NET104.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"), 1L, 1);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            DisplayOrder = 1,
                            Name = "Hung"
                        },
                        new
                        {
                            CategoryID = 2,
                            DisplayOrder = 9,
                            Name = "Banh"
                        },
                        new
                        {
                            CategoryID = 3,
                            DisplayOrder = 5,
                            Name = "Keo"
                        },
                        new
                        {
                            CategoryID = 4,
                            DisplayOrder = 8,
                            Name = "Khoai"
                        },
                        new
                        {
                            CategoryID = 5,
                            DisplayOrder = 5,
                            Name = "Dua hau"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
